# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_id', models.CharField(max_length=1)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Printer_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(choices=[(1, 'Mini'), (2, 'Taz 5'), (3, 'Taz 6'), (4, 'NinjaFlex Mini')], default='Mini', max_length=100)),
                ('serial', models.IntegerField(default=1)),
                ('plastic', models.CharField(choices=[(1, 'Black ABS'), (2, 'Green ABS'), (3, 'Silver ABS'), (4, 'Black NinjaFlex'), (5, 'Green NinjaFlex'), (6, 'Pink NGen Test')], default='Black ABS', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pod',
            name='printer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.Printer_Type'),
        ),
    ]
